services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - APP_ENV=${APP_ENV:-production}
        - WWWUID=${UID:-1000}
        - WWWGID=${GID:-1000}
    image: talpx1/mania_events
    restart: unless-stopped
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - '.:/var/www/html'
      - '~/.ssh:/var/www/.ssh'
    environment:
      - PHP_OPCACHE_ENABLED=${PHP_OPCACHE_ENABLED}
      - PHP_OPCACHE_CLI_ENABLED=${PHP_OPCACHE_CLI_ENABLED}
      - PHP_OPCACHE_MEMORY_CONSUMPTION=${PHP_OPCACHE_MEMORY_CONSUMPTION}
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=${PHP_OPCACHE_MAX_ACCELERATED_FILES}
      - PHP_OPCACHE_MAX_WASTED_PERCENTAGE=${PHP_OPCACHE_MAX_WASTED_PERCENTAGE}
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
      - PHP_OPCACHE_JIT_BUFFER_SIZE=${PHP_OPCACHE_JIT_BUFFER_SIZE}
      - PHP_OPCACHE_JIT_MODE=${PHP_OPCACHE_JIT_MODE}
      - PHP_OPCACHE_REVALIDATE_FREQ=${PHP_OPCACHE_REVALIDATE_FREQ}
    networks:
      - mania_events
    depends_on:
      - db
      - mailpit
    healthcheck:
      test: [ "CMD", "/healthcheck.sh" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    networks:
      - mania_events
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

  mailpit:
    image: 'axllent/mailpit:latest'
    restart: unless-stopped
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - mania_events

networks:
  mania_events:
    driver: bridge
volumes:
  pgsql_data:
